# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'myscheme'
    packageApp: false
    publishJUnitResults: true
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
